apiVersion: v1
kind: Service
metadata:
  name: {{ include "pykasa.fullname" . }}
  labels:
    {{- include "pykasa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: httpkasa
  selector:
    {{- include "pykasa.selectorLabels" . | nindent 4 }}
